# API Gateway port
server.port=9090

# Application name shown in Eureka dashboard
spring.application.name=API-GATEWAY

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable dynamic discovery route support
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route 1: OrderService
# Gateway URL: http://localhost:9090/order
# Actual service: ORDERSERVICE registered in Eureka
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://ORDERSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/order/**

# Route 2: PaymentService
# Gateway URL: http://localhost:9090/payment/...
# Actual service: PAYMENTSERVICE registered in Eureka
spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/payment/**

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
